# Generated by Django 2.2.8 on 2020-07-01 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
