# Generated by Django 2.2.8 on 2020-07-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200701_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='previous',
            field=models.OneToOneField(blank=True, null=True, on_delete=None, related_name='previous_post', to='core.Article'),
        ),
    ]
